#!/bin/sh -f
# this is iTM2_Engine_TeXExec for iTeXMac2 2.0
# © 2004 jlaurens AT users DOT sourceforge DOT net
# This is a TeXExec 5.0 - ConTeXt / PRAGMA ADE 1997-2004 wrapper
echo "THIS IS TEXEXEC WRAPPER; NOT YET IMPLEMENTED, SORRY"
exit

Following the manual:

texexec --make nl en
By default, the main language matches the user interface, which is normally what we expect from a Dutch (nl), English (en) or German (de) version. You can default to another main language and/or font by changing the file cont-usr.tex, but the next alternative works well too:
texexec --make --language=pl,cz,sk --bodyfont=plr en
This will generate a format file with an english user interface, while the main language is Polish (pl) and the default body font is the Polish alternative plr of the Computer Modern Roman (cmr). In addition, Czech and Slovak patterns are loaded. In a similar way you can generate a Czech version (cz and csr). 



TYPESETTING:

POSTPROCESS:

               --alone   bypass utilities (e.g. fmtutil for non-standard fmt'
             --arrange   process and arrange
           --automprun   MetaPost at runtime when needed
               --batch   run in batch mode (don't pause)
          --centerpage   center the page on the paper
               --color   enable color (when not yet enabled)
         --environment   load some environments first
                           =name     : list of environments
                --fast   skip as much as possible
             --figures   typeset figure directory
                           =a        : room for corrections
                           =b        : just graphics
                           =c        : one (cropped) per page
               --final   add a final run without skipping
              --format   fmt file
                           =name     : format file (memory dump)
               --input   input file (if used)
                           =name     : filename
           --interface   user interface
                           =cz       : Czech
                           =de       : German
                           =en       : English
                           =it       : Italian
                           =nl       : Dutch
                           =uk       : Brittish
            --language   main hyphenation language
                           =xx       : standard abbreviation//see enco-, lang-, and font-
             --listing   produce a verbatim listing
                --make   build format files
                --mode   running mode
                           =list     : modes to set
              --module   typeset tex/pl/mp module
MetaPost
            --mpformat   mem file
                           =name     : format file (memory dump)
               --mptex   run an MetaPost plus btex-etex cycle
              --mpxtex   generatet an MetaPostmpx file
                --nomp   don't run MetaPost at all
             --nomprun   don't run MetaPost at runtime

           --noarrange   process but ignore arrange
             --nonstop   run in non stop mode (don't pause)
                --once   run TeX only once (no TeXUtil either)

              --output   specials to use
                           =dvipdfm  : Mark Wicks' dvi to pdf converter
                           =dvipdfmx : Jin-Hwan Cho's extended dvipdfm
                           =dvips    : Thomas Rokicky's dvi to ps converter
                           =dvipsone : YandY's dvi to ps converter
                           =dviwindo : YandY's windows previewer
                           =pdftex   : Han The Than's pdf backend
                 --pdf   produce PDF directly using pdf(e)tex

               --pages   pages to output
                           =even     : even pages
                           =odd      : odd pages
                           =x,y:z    : pages x and y to z
               --paper   paper input and output format
                           =a4a3     : A4 printed on A3
                           =a5a4     : A5 printed on A4

              --passon   switches to pass to TeX (--src for MikTeX)

                --path   document source path
                           =string   : path

          --pdfarrange   arrange pdf pages
          --pdfcombine   combine pages to one page
             --pdfcopy   scale pages down/up
           --pdfselect   select pdf pages
               --print   page imposition scheme
                           =down     : 2 rotated pages per sheet doubleside
                           =up       : 2 pages per sheet doublesided


						TYPESETING
              --result   resulting file
                           =name     : filename
                --runs   maximum number of TeX runs
                           =n        : number of runs

         --screensaver   turn graphic file into a (pdf) full screen file
             --setfile   load environment (batch) file
              --suffix   resulting file suffix
                           =string   : suffix

                 --tex   TeX binary
                           =name     : binary of executable
             --texroot   root of tex trees
                           =path     : tex root
             --textree   additional texmf tree to be used
                           =path     : subpath of tex root
             --texutil   force TeXUtil run
           --usemodule   load some modules first
                           =name     : list of modules

              --silent   minimize (status) messages
             --verbose   shows some additional info
             --version   display various version information

           --xmlfilter   apply XML filter
                           =name     : list of filters
