#!/bin/sh
# this is iTM2_Compile_mp for iTeXMac2 2.0
# © 2004 jlaurens AT users DOT sourceforge DOT net
# This is a MetaPost 0.641 (Web2C 7.5.3) wrapper
#echo "iTM2: STARTING $0"
iTM2_MP_Compile_Version=1.0
"$iTM2_CMD_Notify" comment "Welcome to `basename "$0"` version $iTM2_MP_Compile_Version
This is iTeXMac2 built in script to process MetaPost document
Override my behaviour by editing the project settings
© 2005 jlaurens AT users DOT sourceforge DOT net"
iTM2_Engine_mpost
exit 0
