#!/bin/sh
# this is iTM2_Engine_MPS2PDF for iTeXMac2
# © 2005 jlaurens AT users DOT sourceforge DOT net
# This is a MPS2PDF based on mps2eps
#echo "iTM2: STARTING $0"
printenv
iTM2_MPS2PDF_Engine_Version=1.0
iTM2MPS2PDFEngineUsage()
{
iTM2_USAGE="Welcome to `basename "$0"` version ${iTM2_MPS2PDF_Engine_Version}
This is iTeXMac2 built in script to wrap the tex engine
(`which "$0"`)
© 2004 jlaurens AT users DOT sourceforge DOT net
Usage: `basename "$0"` --input INPUT --dvips DVIPS_OPT with environment variables
	TWSMaster: the main input file
	iTM2_MPS2PDF_USE_dvips_options: 1 or 0, default to 0
	iTM2_MPS2PDF_dvips_options: more arguments for dvips"
echo "$iTM2_USAGE"
exit 0
}
"$iTM2_CMD_Notify" comment "Welcome to `basename "$0"` version ${iTM2_MPS2PDF_Engine_Version}
(`which "$0"`)
This is iTeXMac2 built in script to convert MetaPost output to PDF
© 2005 jlaurens AT users DOT sourceforge DOT net"
if [ "${iTM2_Debug:-0}" != "0" ]
then
	"$iTM2_CMD_Notify" start comment
	"$iTM2_CMD_Notify" echo "The $0 specific environment is:"
	for iTM2VAR in ${!iTM2_MPS2PDF_*}
	do
		"$iTM2_CMD_Notify" echo "${iTM2VAR} is: ${!iTM2VAR}"
	done
	"$iTM2_CMD_Notify" stop comment
fi
while [ $# -gt 0 ]
do
	echo "1: $1"
    case $1 in
        --input)
			shift 1
			if [ $# -gt 0 ]
			then
				TWSMaster=$1
			else
				iTM2MPS2PDFEngineUsage
			fi
			;;
        --dvips)
			shift 1
			if [ $# -gt 0 ]
			then
				iTM2_MPS2PDF_USE_dvips_options="1"
				iTM2_MPS2PDF_dvips_options=$1
			else
				iTM2MPS2PDFEngineUsage
			fi
			;;
        *) iTM2MPS2PDFEngineUsage
			;;
    esac
	shift 1
done
"$iTM2_CMD_Notify" comment "TWSMaster is: ${TWSMaster}"
pushd "$(dirname "${TWSMaster}")"
INPUT="$(basename "${TWSMaster}")"
TEXBASE=${INPUT}_trash_me_$$
TEXFILE=${TEXBASE}.tex
EPSFILE=${INPUT}.eps
cat > $TEXFILE <<EOF
\nopagenumbers
\input epsf
\centerline{\epsfbox{$INPUT}}
\end
EOF
if [ "${iTM2_MPS2PDF_USE_tex_options:-0}" != "0" ] && [ ${#iTM2_MPS2PDF_tex_options} -ne 0 ]
then
	tex ${iTM2_MPS2PDF_tex_options} -interaction batchmode $TEXFILE
else
	tex -interaction batchmode $TEXFILE
fi
if [ "${iTM2_MPS2PDF_USE_dvips_options:-0}" != "0" ] && [ ${#iTM2_MPS2PDF_dvips_options} -ne 0 ]
then
    dvips ${iTM2_MPS2PDF_dvips_options} -E -j -o $EPSFILE $TEXBASE
else
    dvips -E -j -o $EPSFILE $TEXBASE
fi
echo LISTING
pwd
ls
ls *trash_me*
rm -f *trash_me*
epstopdf  $EPSFILE
popd
if [ "${iTM2_Debug:-0}" != "0" ]
then
	"$iTM2_CMD_Notify" comment "$0 complete."
fi
exit 0
