#!/bin/sh
if [ $# == 0 ]
then
    "$0" --help
    exit 1
fi
while [ $# -gt 0 ]
do
	case $1 in
		-h|--help)
            echo "usage $0 --name newPlugInName"
            exit 0
		;;
		-c|--convert)
            shift 1
            if [ $# -gt 0 ]
            then
                COMMAND="$1"
            else
                echo "Missing command, bailing out"
                exit 6				
            fi
		;;
		-n|--name)
			shift 1
			if [ $# -gt 0 ]
			then
				iTM2_NEW_NAME="$1"
        		TEMP="`echo "${iTM2_NEW_NAME}" | sed -e /\ /s//XX/g`"
				if [ ${#TEMP} -gt ${#iTM2_NEW_NAME} ]
				then
				    echo "${TEMP}"
                    echo "Forbidden spaces in \"${iTM2_NEW_NAME}\", bailing out"
                    exit 4				
				fi
				if [ "`dirname "${iTM2_NEW_NAME}"`" != "." ]
				then
                    echo "Forbidden / in \"${iTM2_NEW_NAME}\", bailing out"
                    exit 5				
				fi
			else
                "$0" -help
                exit 2
			fi
		;;
		*)
            "$0" --help
            exit 3
	esac
	shift 1
done
if ! [ ${#iTM2_NEW_NAME} -gt 0 ]
then
    "$0" --help
    exit 10
fi
if [ ${#COMMAND} -gt 0 ]
then
    TARGETS=`ls -1`
    IFS="
    "
    for TARGET in ${TARGETS}
    do
        if [ -d "${TARGET}" ]
        then
            pushd "${TARGET}"
            "${COMMAND}" --convert "${COMMAND}" --name "${iTM2_NEW_NAME}"
            popd
        elif [ "${TARGET}" != "${0##*/}" ]
        then
            echo "=====  Converting: ${TARGET}"
            sed -e /iTM2TEMPLATE_PLUGIN/s//${iTM2_NEW_NAME}/g -i "" "${TARGET}"
        fi
        NEWTARGET=`echo "${TARGET}" | sed -e /iTM2TEMPLATE_PLUGIN/s//${iTM2_NEW_NAME}/g`
        echo "NEWTARGET is: ${NEWTARGET}"
        if [ "${NEWTARGET}" != "${TARGET}" ]
        then
            mv "${TARGET}" "${NEWTARGET}"
        fi
    done
    exit 0
fi
iTM2_MY_FOLDER="`dirname "$0"`/.."
iTM2_FULL_NEW_NAME="${iTM2_MY_FOLDER}/${iTM2_NEW_NAME}"
if [ -e "${iTM2_FULL_NEW_NAME}" ]
then
    echo "${iTM2_FULL_NEW_NAME} already exists, bailing out"
    exit 12
fi
iTM2_TEMPLAT_SOURCE="${iTM2_MY_FOLDER}/iTM2TEMPLATE_PLUGIN"
if ! [ -d "${iTM2_TEMPLAT_SOURCE}" ]
then
    echo "Missing iTM2TEMPLATE_PLUGIN, bailing out"
    exit 13
fi
cp -R "${iTM2_TEMPLAT_SOURCE}" "${iTM2_FULL_NEW_NAME}"
if ! [ -d "${iTM2_FULL_NEW_NAME}" ]
then
    echo "Could not duplicate the source template plg in, bailing out"
    exit 14
fi
find "${iTM2_FULL_NEW_NAME}" -regex ".*/\.DS_Store" -print | xargs rm -Rf
find "${iTM2_FULL_NEW_NAME}" -regex ".*/CVS" -print | xargs rm -Rf
find "${iTM2_FULL_NEW_NAME}" -regex ".*/\.svn" -print | xargs rm -Rf
COMMAND="`pwd`/$0"
if ! [ -x ${COMMAND} ]
then
    COMMAND="$0"
fi
cd "${iTM2_FULL_NEW_NAME}"
"${COMMAND}" --convert "${COMMAND}" --name "${iTM2_NEW_NAME}"
exit 0
