#!/bin/sh -f
# this is iTM2_Engine_PDFTeX for iTeXMac2 2.0
# © 2005 jlaurens@users.sourceforge.net
# This is a pdfeTeX 3.141592-1.20a-2.2 (Web2C 7.5.3) wrapper
iTM2_PDFTeX_Engine_Version=1.0
iTM2PDFTeXEngineUsage()
{
iTM2_USAGE="Welcome to `basename "$0"` version ${iTM2_PDFTeX_Engine_Version}
This is iTeXMac2 built in script to wrap the pdftex engine
(`which "$0"`)
© 2005 jlaurens@users.sourceforge.net
Usage: `basename "$0"` with environment variables
	TWSMaster: the main input file
	iTM2_Continuous_Compile: 1 or 0
	iTM2_USE_output_directory: 1 or 0 (common)
	iTM2_output_directory: the common output directory
	iTM2_PDFTeX_ini: 1 or 0, be initex, for dumping formats
	iTM2_PDFTeX_mltex: 1 or 0, enable MLTeX extensions such as \charsubdef
	iTM2_PDFTeX_enc: 1 or 0,
	iTM2_PDFTeX_MoreArgument:
	iTM2_PDFTeX_mktex: 1 or 0,
	iTM2_PDFTeX_USE_output_directory: 1 or 0
	iTM2_PDFTeX_output_directory:
	iTM2_PDFTeX_output_format: \"pdf\" or \"dvi\"
	iTM2_PDFTeX_fmt: = FMTNAME, use the value instead of program name or a %& line
	iTM2_PDFTeX_parse_first_line: 1 or 0, parse of the first line of the input file
	iTM2_PDFTeX_USE_progname: 1 or 0,
	iTM2_PDFTeX_progname: = STRING, set program (and fmt) name to STRING
	iTM2_PDFTeX_USE_jobname: 1 or 0,
	iTM2_PDFTeX_jobname: = STRING, set the job name to STRING
	iTM2_PDFTeX_shell_escape: 1 or 0, enable \write18{SHELL COMMAND}
	iTM2_PDFTeX_PDFSYNC: 1 or 0,
	iTM2_PDFTeX_src_specials: 1 or 0, insert source specials into the DVI file
	iTM2_PDFTeX_src_specials_where_no_cr: 1 or 0,
	iTM2_PDFTeX_src_specials_where_no_display: 1 or 0,
	iTM2_PDFTeX_src_specials_where_no_hbox: 1 or 0,
	iTM2_PDFTeX_src_specials_where_no_parent: 1 or 0,
	iTM2_PDFTeX_src_specials_where_no_par: 1 or 0,
	iTM2_PDFTeX_src_specials_where_no_math: 1 or 0,
	iTM2_PDFTeX_src_specials_where_no_vbox: 1 or 0,
	iTM2_PDFTeX_USE_output_comment: 1 or 0,
	iTM2_PDFTeX_output_comment:
	iTM2_PDFTeX_USE_translate_file: 1 or 0,
	iTM2_PDFTeX_translate_file := TCXNAME, use the TCX file TCXNAME
	iTM2_PDFTeX_PARSE_translate_file: 1 or 0,
	iTM2_PDFTeX_recorder: 1 or 0, enable filename recorder
	iTM2_PDFTeX_file_line_error: 1 or 0, print file:line:error style messages
	iTM2_PDFTeX_halt_on_error: 1 or 0,
	iTM2_PDFTeX_interaction: batchmode/nonstopmode/scrollmode/errorstopmode, set interaction mode
	iTM2_PDFTeX_kpathsea_debug:
	iTM2_PDFTeX_MoreArgument: more arguments"
echo "$iTM2_USAGE"
exit 0
}
"$iTM2_CMD_Notify" comment "Welcome to `basename "$0"` version ${iTM2_PDFTeX_Engine_Version}
This is iTeXMac2 built in script to wrap the pdftex engine
© 2005 jlaurens@users.sourceforge.net"
if [ "${iTM2_Debug:-0}" != "0" ]
then
	"$iTM2_CMD_Notify" start comment
	"$iTM2_CMD_Notify" echo "The $0 specific environment is:"
	for iTM2VAR in ${!iTM2_PDFTeX_*}
	do
		"$iTM2_CMD_Notify" echo "${iTM2VAR} is: ${!iTM2VAR}"
	done
	"$iTM2_CMD_Notify" stop comment
fi

iTM2_PDFTeX_Engine="pdftex"
iTM2_PDFTeX_EnginePath="`which "${iTM2_PDFTeX_Engine}"`"
if ! [ -x "${iTM2_PDFTeX_EnginePath}" ]
then
	"$iTM2_CMD_Notify" error "Unknown command ${iTM2_PDFTeX_Engine}."
	iTM2PDFTeXEngineUsage
fi
EXTENSION="$(basename ${TWSMaster})"
EXTENSION="${EXTENSION##*.}"
if [ ${#EXTENSION} -ne 0 ]
then
	EXTENSION="$(echo "${EXTENSION}" | tr 'TEX' 'tex')"
	if [ "${EXTENSION}" != "tex" ]
	then
		TWSMaster="${TWSMaster%.*}.tex"
	fi
fi
if ! [ -r "${TWSMaster}" ]
then
	"$iTM2_CMD_Notify" error "No readable file at ${TWSMaster} (in $(pwd) / ${PWD})."
	iTM2PDFTeXEngineUsage
fi
"$iTM2_CMD_Notify" comment "TWSMaster is: ${TWSMaster}"
pushd "$(dirname "${TWSMaster}")"
INPUT_DIRECTORY="${PWD}"
popd
INPUT="$(basename "${TWSMaster}")"
iTM2_PDFTeX_Arguments=""
if [ "${iTM2_PDFTeX_USE_jobname:-0}" != "0" ] && [ ${#iTM2_PDFTeX_jobname} -ne 0 ]
then
	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -jobname \"${iTM2_PDFTeX_jobname}\""
	OUTPUT="${iTM2_PDFTeX_jobname}"
else
	OUTPUT="${INPUT%.*}"
fi
if [ "${iTM2_PDFTeX_ini:-0}" != "0" ]
then
	iTM2_PDFTeX_Arguments="-ini"
	if [ "${iTM2_PDFTeX_enc:-0}" != "0" ]
	then
		iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -enc"
	fi
	if [ "${iTM2_PDFTeX_mltex:-0}" != "0" ]
	then
		iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -mltex"
	fi
	if [ "${iTM2_PDFTeX_output_format:-pdf}" == "dvi" ]
	then
		iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -output-format dvi"
	else
		iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -output-format pdf"
	fi
else
	if [ "${iTM2_PDFTeX_output_format:-pdf}" == "dvi" ]
	then
		iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -output-format ${iTM2_PDFTeX_output_format}"
		if [ "${iTM2_PDFTeX_USE_output_comment:-0}" != "0" ] && [ ${#iTM2_PDFTeX_output_comment} -ne 0 ]
		then
			iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -output-comment \"${iTM2_PDFTeX_output_comment}\""
		fi
		if [ "${iTM2_PDFTeX_src_specials:-0}" != "0" ]
		then
			iTM2_SRC_SPECIALS=""
			if [ "${iTM2_PDFTeX_src_specials_no_cr:-0}" == "0" ]
			then
				if [ ${#iTM2_SRC_SPECIALS} -gt 0 ]
				then
					iTM2_SRC_SPECIALS="${iTM2_SRC_SPECIALS},cr"
				else
					iTM2_SRC_SPECIALS="cr"
				fi
			fi
			if [ "${iTM2_PDFTeX_src_specials_no_par:-0}" == "0" ]
			then
				if [ ${#iTM2_SRC_SPECIALS} -gt 0 ]
				then
					iTM2_SRC_SPECIALS="${iTM2_SRC_SPECIALS},par"
				else
					iTM2_SRC_SPECIALS="par"
				fi
			fi
			if [ "${iTM2_PDFTeX_src_specials_no_display:-0}" == "0" ]
			then
				if [ ${#iTM2_SRC_SPECIALS} -gt 0 ]
				then
					iTM2_SRC_SPECIALS="${iTM2_SRC_SPECIALS},display"
				else
					iTM2_SRC_SPECIALS="display"
				fi
			fi
			if [ "${iTM2_PDFTeX_src_specials_no_math:-0}" == "0" ]
			then
				if [ ${#iTM2_SRC_SPECIALS} -gt 0 ]
				then
					iTM2_SRC_SPECIALS="${iTM2_SRC_SPECIALS},math"
				else
					iTM2_SRC_SPECIALS="math"
				fi
			fi
			if [ "${iTM2_PDFTeX_src_specials_no_hbox:-0}" == "0" ]
			then
				if [ ${#iTM2_SRC_SPECIALS} -gt 0 ]
				then
					iTM2_SRC_SPECIALS="${iTM2_SRC_SPECIALS},hbox"
				else
					iTM2_SRC_SPECIALS="hbox"
				fi
			fi
			if [ "${iTM2_PDFTeX_src_specials_no_vbox:-0}" == "0" ]
			then
				if [ ${#iTM2_SRC_SPECIALS} -gt 0 ]
				then
					iTM2_SRC_SPECIALS="${iTM2_SRC_SPECIALS},vbox"
				else
					iTM2_SRC_SPECIALS="vbox"
				fi
			fi
			if [ "${iTM2_PDFTeX_src_specials_no_parent:-0}" == "0" ]
			then
				if [ ${#iTM2_SRC_SPECIALS} -gt 0 ]
				then
					iTM2_SRC_SPECIALS="${iTM2_SRC_SPECIALS},parent"
				else
					iTM2_SRC_SPECIALS="parent"
				fi
			fi
			if [ ${#iTM2_SRC_SPECIALS} -gt 0 ]
			then
				iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -src-specials=${iTM2_SRC_SPECIALS}"
			else
				iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -src-specials"
			fi
		fi
	else
		iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -output-format pdf"
		if [ "${iTM2_PDFTeX_PDFSYNC:-0}" != "0" ]
		then
			"$iTM2_CMD_Notify" error "PDFSYNC no yet supported"
		fi
	fi
fi
if [ "${iTM2_PDFTeX_USE_output_directory:-0}" != "0" ] && [ ${#iTM2_PDFTeX_output_directory} -ne 0 ]
then
	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -output-directory \"${iTM2_PDFTeX_output_directory}\""
elif [ "${iTM2_PDFTeX_USE_output_directory:-0}" != "0" ] && [ ${#iTM2_PDFTeX_output_directory} -ne 0 ]
then
	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -output-directory \"${iTM2_PDFTeX_output_directory}\""
fi
iTM2_PDFTeX_fmt="`echo ${iTM2_PDFTeX_fmt} | tr [:upper:] [:lower:]`"
if [ "${iTM2_PDFTeX_parse_first_line:-0}" != "0" ]
then
	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -parse-first-line"
	if [ "${iTM2_PDFTeX_USE_translate_file:-0}" != "0" ] && [ ${#iTM2_PDFTeX_translate_file} -gt 0 ]
	then
		if [ "${iTM2_PDFTeX_PARSE_translate_file:-0}" != "0" ]
		then
			iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -default-translate-file"
		else
			iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -translate-file"
		fi
		iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} \"${iTM2_PDFTeX_translate_file}\""
	fi
	if [ "${iTM2_PDFTeX_USE_progname:-0}" != "0" ] && [ ${#iTM2_PDFTeX_progname} -ne 0 ]
	then
		iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -progname ${iTM2_PDFTeX_progname}"
	fi
else
	if [ "${iTM2_PDFTeX_USE_progname:-0}" != "0" ] && [ ${#iTM2_PDFTeX_progname} -ne 0 ]
	then
		iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -progname ${iTM2_PDFTeX_progname}"
		if [ "${iTM2_PDFTeX_fmt}" == "plain" ]
		then
			iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -fmt pdftex"
		elif [ ${#iTM2_PDFTeX_fmt} -gt 0 ]
		then
			if [ "${iTM2_PDFTeX_fmt:0:3}" != "pdf" ]
			then
				iTM2_PDFTeX_pdffmt="pdf${iTM2_PDFTeX_fmt}"
				if [ "$(kpsewhich "${iTM2_PDFTeX_pdffmt}.fmt")" != "" ]
				then
					iTM2_PDFTeX_fmt="${iTM2_PDFTeX_pdffmt}"
				fi
			fi
			iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -fmt ${iTM2_PDFTeX_fmt}"
		fi
	elif [ "${iTM2_PDFTeX_fmt}" == "plain" ]
	then
		iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -progname pdftex"
	elif [ ${#iTM2_PDFTeX_fmt} -gt 0 ]
	then
		if [ "${iTM2_PDFTeX_fmt:0:3}" != "pdf" ]
		then
			iTM2_PDFTeX_pdffmt="pdf${iTM2_PDFTeX_fmt}"
			if [ "$(kpsewhich "${iTM2_PDFTeX_pdffmt}.fmt")" != "" ]
			then
				iTM2_PDFTeX_fmt="${iTM2_PDFTeX_pdffmt}"
			fi
		fi
		iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -progname ${iTM2_PDFTeX_fmt}"
	fi
	if [ "${iTM2_PDFTeX_USE_translate_file:-0}" != "0" ] && [ ${#iTM2_PDFTeX_translate_file} -gt 0 ]
	then
		iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -translate-file \"${iTM2_PDFTeX_translate_file}\""
	fi
fi
if [ "${iTM2_PDFTeX_recorder:-0}" != "0" ]
then
	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -recorder"
fi
if [ "${iTM2_PDFTeX_file_line_error:-0}" != "0" ]
then
	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -file-line-error"
fi
if [ "${iTM2_PDFTeX_halt_on_error:-0}" != "0" ]
then
	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -halt-on-error"
elif [ "${iTM2_ContinuousCompile:-0}" != "0" ]
then
	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -halt-on-error"
fi
if [ "${iTM2_PDFTeX_kpathsea_debug:-0}" != "0" ]
then
	"$iTM2_CMD_Notify" error "-kpathsea-debug no yet supported."
fi
if [ ${#iTM2_PDFTeX_interaction} -gt 0 ] && [ "${iTM2_ContinuousCompile:-0}" == "0" ]
then
	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} -interaction ${iTM2_PDFTeX_interaction}"
fi
if [ "${iTM2_PDFTeX_USE_MoreArgument:-0}" != "0" ] && [ ${#iTM2_PDFTeX_MoreArgument} -ne 0 ]
then
	iTM2_PDFTeX_Arguments="${iTM2_PDFTeX_Arguments} \"${iTM2_PDFTeX_MoreArgument}\""
fi
pushd "${INPUT_DIRECTORY}"
"$iTM2_CMD_Notify" comment "Performing  ${iTM2_PDFTeX_EnginePath} ${iTM2_PDFTeX_Arguments} \"${INPUT}\""
${iTM2_PDFTeX_EnginePath} ${iTM2_PDFTeX_Arguments} "${INPUT}"
popd
if [ "${iTM2_PDFTeX_output_format:-pdf}" == "dvi" ] # no external viewer supported...
then
	"$iTM2_CMD_Notify" comment "Swicthing to a dvi to ps filter for ${INPUT_DIRECTORY}/${OUTPUT%.*}"
	iTM2_Command_Compile --master "${INPUT_DIRECTORY}/${OUTPUT%.*}" --switch dvi
else
	"${iTM2_TemporaryDirectory}/bin/iTeXMac2" update -file "${INPUT_DIRECTORY}/${OUTPUT%.*}.pdf" -project "${TWSProjectDirectory}/${TWSProjectName}"
fi
if [ "${iTM2_Debug:-0}" != "0" ]
then
	"$iTM2_CMD_Notify" comment "$0 complete."
fi
exit 0
