#!/usr/bin/env bash
# this is bbedit shell script for iTeXMac 1.3 version 0.1
# © 2006 jlaurens AT users DOT sourceforge DOT net
command="/usr/bin/bbedit"
if [ ${#file} -gt 0 ]
then
    options="+${line:-0}"
    echo "\"${command}\" ${options} \"${file}\""
    "${command}" ${options} "${file}"
else
    "${command}"
fi
exit