#!/bin/sh -f
# this is iTM2_Engine_LaTeXDocExtractor wrapper
# © 2006 jlaurens AT users DOT sourceforge DOT net
iTM2_Engine_LaTeXDocExtractor_Version=1.0
iTM2LaTeXDocExtractorEngineUsage()
{
iTM2_USAGE="Welcome to $(basename "$0") version ${iTM2_Engine_LaTeXDocExtractor_Version}
This is iTeXMac2 built in script to wrap the LaTeX Documentation Extractor engine
($(which "$0"))
© 2006 jlaurens AT users DOT sourceforge DOT net
Usage: $(basename "$0") with environment variables
	TWSMaster: the main input file, with an \"ins\" path extension"
echo "$iTM2_USAGE"
}
"$iTM2_CMD_Notify" comment "Welcome to $(basename "$0") version ${iTM2_Engine_LaTeXDocExtractor_Version}
This is iTeXMac2 built in script to wrap the LaTeX Installation engine
© 2006 jlaurens AT users DOT sourceforge DOT net"
iTM2_LaTeXDocExtractor_Engine="latex"
iTM2_LaTeXDocExtractor_EnginePath="$(which "${iTM2_LaTeXDocExtractor_Engine}")"
if ! [ -x "${iTM2_LaTeXDocExtractor_EnginePath}" ]
then
	"$iTM2_CMD_Notify" error "Unknown command ${iTM2_LaTeXDocExtractor_Engine}."
	iTM2LaTeXDocExtractorEngineUsage
	exit 1
fi
# removing the faraway project directory if any, first remove the trailing /'s
iTM2_temp="${iTM2_Faraway_Projects_Directory}"
iTM2_Faraway_Projects_Directory="$(echo ${iTM2_Faraway_Projects_Directory} | sed -e 's/\/$//')"
while [ ${#iTM2_temp} -gt ${#iTM2_Faraway_Projects_Directory} ]
do
	iTM2_temp="${iTM2_Faraway_Projects_Directory}"
	iTM2_Faraway_Projects_Directory="$(echo "${iTM2_Faraway_Projects_Directory}" | sed -e 's/\/$//')"
done
TWSProjectDirectory="${TWSProjectDirectory#${iTM2_Faraway_Projects_Directory}}"
iTM2_temp="${TWSProjectDirectory#${iTM2_Faraway_Projects_Directory}}"
if [ ${#iTM2_temp} -lt ${#TWSProjectDirectory} ]
then
	TWSProjectDirectory="${iTM2_temp%/*.texd}"
fi
"$iTM2_CMD_Notify" comment "TWSProjectDirectory is: ${TWSProjectDirectory}"
if ! [ -d "${TWSProjectDirectory}" ]
then
	exit 1
fi
pushd "${TWSProjectDirectory}"
EXTENSION="${TWSMaster##*.}"
EXTENSION="$(echo "${EXTENSION}" | tr 'DTX' 'dtx')"
if [ "${EXTENSION}" != "dtx" ]
then
	popd
	exit 2
fi
"$iTM2_CMD_Notify" comment "Performing  ${iTM2_LaTeXDocExtractor_EnginePath} \"${TWSMaster}\""
"$iTM2_CMD_Notify" comment "Current directory is: $(pwd)"
${iTM2_LaTeXDocExtractor_EnginePath} "${TWSMaster}"
popd
if [ "${iTM2_Debug:-0}" != "0" ]
then
	"$iTM2_CMD_Notify" comment "$0 complete."
fi
# Missing a notification of the end of the work with success or failure
exit 0
