#!/usr/bin/env bash
# this is alphax shell script for iTeXMac 1.3 version 0.1
# © 2003 jlaurens@users.sourceforge.net
base="/Applications/Emacs.app/Contents/Resources/bin/Emacs-server"
if [ -x "~$base" ]
then
    command="~$base"
elif [ -x "$base" ]
then
    command="$base"
else
    base="/Applications/Emacs.app/Contents/MacOS/bin/Emacs-server"
    if [ -x "~$base" ]
    then
        command="~$base"
    elif [ -x "$base" ]
        command="$base"
    else
        echo "Don't know where is emacs,"
        echo "Please make your own command"
        return 1
    fi
fi
if [ ${#file} -gt 0 ]
then
    echo "`pwd`"
    cd "`dirname "${file}"`"
    echo "`pwd`"
    options=""
    if [ ${line:--1} -gt 0 ]
    then
        options="+${line}"
    fi
    echo "\"${command}\" ${options} \"${file##*/}\""
    ${command} ${options} "${file##*/}"
else
    "${command}"
fi
exit
