#!/bin/sh -f
# this is iTM2_Command_Typeset for iTeXMac2 1.4
# © 2004 jlaurens@users.sourceforge.net
iTM2_Typeset_version="1.0"
iTM2_Typeset_USAGE="Welcome to `basename "$0"` version ${iTM2_Typeset_version}
This is iTeXMac2 built in script to typeset
© 2004 jlaurens@users.sourceforge.net
Usage: `basename "$0"` options input where options are
       -h, --help: print this message and return.
       -i input, --input input: input is the input file.
       -m mode, --mode mode: mode is the typesetting mode.
       -q, --quiet: runs silently.
Typesetting the given input according to the given mode."
iTM2_Typeset_RunSilently="${iTM2_RunSilently}"
while [ $# -gt 0 ]
do
	case $1 in
		-h|--help)
			"$iTM2_CMD_Notify" comment "$iTM2_Typeset_USAGE"
		;;
		-i|--input)
                        shift 1
                        if [ $# -gt 0 ]
                        then
                                iTM2_Typeset_Input="$1"
                        else
								"$iTM2_CMD_Notify" comment "$iTM2_Typeset_USAGE"
                        fi
		;;
		-q|--quiet)
			iTM2_Typeset_RunSilently="YES"
		;;
		*)
			"$iTM2_CMD_Notify" warning "$iTM2_Typeset_USAGE"
	esac
	shift 1
done
if [ "${iTM2_Typeset_RunSilently:-0}" = "0" ]
then
        "$iTM2_CMD_Notify" comment "Welcome to `basename "$0"` version ${iTM2_Typeset_version}
This is iTeXMac2 built in script to typeset
© 2005 jlaurens@users.sourceforge.net"
fi
if [ "${iTM2_IS_TYPESETTING:-0}" != "0" ]
then
    "$iTM2_CMD_Notify" error "Recursive call forbidden (`basename "$0"`)"
    exit 1
else
    export iTM2_IS_TYPESETTING=1
fi
if [ "${iTM2_Debug:-0}" != "0" ]
then
	"$iTM2_CMD_Notify" start comment
	"$iTM2_CMD_Notify" echo "The $0 specific environment is:"
	for iTM2VAR in ${!iTM2_Typeset*}
	do
		echo "${iTM2VAR} is: ${!iTM2VAR}"
	done
	"$iTM2_CMD_Notify" stop comment
fi
if [ ${#iTM2_Typeset_Input} -eq 0 ]
then
    iTM2_Typeset_Input="${TWSMaster}"
fi
iTM2_Old_Input="${TWSMaster}"
TWSMaster="${iTM2_Typeset_Input}"
case "${iTM2_Typeset_Mode}" in
    plain)
        iTM2_Command_Compile
    ;;
    latex)
        iTM2_Command_Compile
        iTM2_Command_Compile
    ;;
    latex-book)
        iTM2_Command_Compile
        iTM2_Command_Bibliography
        iTM2_Command_Index
        iTM2_Command_Glossary
        iTM2_Command_Compile
        iTM2_Command_Compile
    ;;
    latex-complete)
        "$iTM2_CMD_Notify" warning "THE COMPLETE LATEX MODE IS NOT YET IMPLEMENTED, BOOK MODE USED INSTEAD"
        iTM2_Command_Compile
        iTM2_Command_Bibliography
        iTM2_Command_Index
        iTM2_Command_Glossary
        iTM2_Command_Compile
        iTM2_Command_Compile
    ;;
    *)
        "$iTM2_CMD_Notify" warning "Unknown mode: ${iTM2_Typeset_Mode}"
        iTM2_Command_Compile
    ;;
esac
status=$?
TWSMaster="${iTM2_Old_Input}"
#conclusion?
if [ "${iTM2_Typeset_RunSilently:-0}" == "0" ]
then
        "$iTM2_CMD_Notify" comment "`basename "$0"` complete"
fi
exit $status
