#!/usr/bin/env bash
# this is iTM2_Format_Observer for iTeXMac2 2.0
# © 2004 jlaurens AT users DOT sourceforge DOT net
# no doc yet
iTM2_WEB2C="`kpsewhich pdflatex.fmt`"
cd "`dirname ${iTM2_WEB2C}`"
iTM2_ALL="`find . -name "*.fmt"`"
for iTM2_FILE in ${iTM2_ALL}; do
    iTM2_NAME=${iTM2_FILE##*/}
    iTM2_CORE=${iTM2_NAME%%.*}
    iTM2_TMP=`perl -e "print readlink(\"$iTM2_FILE\");"`
    if [ ${#iTM2_TMP} -eq 0 ]
    then
	iTM2_TMP="${iTM2_CORE}"
    else
	iTM2_TMP=${iTM2_TMP##*/}
	iTM2_TMP=${iTM2_TMP%%.*}
    fi
    iTM2_LOG="${iTM2_TMP}.log"
    if [ -r ${iTM2_LOG} ]
    then
	if [ "`grep -c '^This is pdfeTeX' "${iTM2_LOG}"`" -gt 0 ]
	then
	    if [ ${#iTM2_pdfeTeX} -gt 0 ]
	    then
		iTM2_pdfeTeX="$iTM2_pdfeTeX$IFS$iTM2_CORE"
	    else
		iTM2_pdfeTeX="$iTM2_CORE"
	    fi
	elif [ "`grep -c '^This is TeX' "${iTM2_LOG}"`" -gt 0 ]
	then
	    if [ ${#iTM2_TeX} -gt 0 ]
	    then
		iTM2_TeX="$iTM2_TeX$IFS$iTM2_CORE"
	    else
		iTM2_TeX="$iTM2_CORE"
	    fi
	else
	    if [ ${#iTM2_Other} -gt 0 ]
	    then
		iTM2_Other="$iTM2_Other$IFS$iTM2_CORE"
	    else
		iTM2_Other="$iTM2_CORE"
	    fi
	fi
    else
	if [ ${#iTM2_Other} -gt 0 ]
	then
	    iTM2_Other="$iTM2_Other$IFS$iTM2_CORE"
	else
	    iTM2_Other="$iTM2_CORE"
	fi
    fi
done
iTM2_ALL="`find . -name "*.base"`"
for iTM2_FILE in ${iTM2_ALL}; do
    iTM2_NAME=${iTM2_FILE##*/}
    iTM2_CORE=${iTM2_NAME%%.*}
    if [ ${#iTM2_MetaFont} -gt 0 ]
    then
	iTM2_MetaFont="$iTM2_MetaFont$IFS$iTM2_CORE"
    else
	iTM2_MetaFont="$iTM2_CORE"
    fi
done
iTM2_ALL="`find . -name "*.mem"`"
for iTM2_FILE in ${iTM2_ALL}; do
    iTM2_NAME=${iTM2_FILE##*/}
    iTM2_CORE=${iTM2_NAME%%.*}
    if [ ${#iTM2_MetaPost} -gt 0 ]
    then
	iTM2_MetaPost="$iTM2_MetaPost$IFS$iTM2_CORE"
    else
	iTM2_MetaPost="$iTM2_CORE"
    fi
done
echo '<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>TeX</key>
	<array>'
for iTM2_FILE in ${iTM2_TeX}; do
echo "		<string>${iTM2_FILE}</string>"
done
echo '	</array>
	<key>pdfeTeX</key>
	<array>'
for iTM2_FILE in ${iTM2_pdfeTeX}; do
echo "		<string>${iTM2_FILE}</string>"
done
echo '	</array>
	<key>Other</key>
	<array>'
for iTM2_FILE in ${iTM2_Other}; do
echo "		<string>${iTM2_FILE}</string>"
done
echo '	</array>
	<key>MetaPost</key>
	<array>'
for iTM2_FILE in ${iTM2_MetaPost}; do
echo "		<string>${iTM2_FILE}</string>"
done
echo '	</array>
	<key>MetaFont</key>
	<array>'
for iTM2_FILE in ${iTM2_MetaFont}; do
echo "		<string>${iTM2_FILE}</string>"
done
echo ' 	</array>
</dict>
</plist>'
exit
