#!/bin/sh -f
# this is alphax shell script for iTeXMac 1.3 version 0.1
# © 2003 jlaurens@users.sourceforge.net
command="bbeditlite"
if [ ${#file} -gt 0 ]
then
    echo "`pwd`"
    cd "`dirname "${file}"`"
    echo "`pwd`"
    options=""
    if [ ${line:--1} -gt 0 ]
    then
        options="+${line}"
    fi
    echo "\"${command}\" ${options} \"${file##*/}\""
    ${command} ${options} "${file##*/}"
else
    "${command}"
fi
exit
