#!/bin/sh -f
# this is iTM2_Engine_LaTeXDocExtractor wrapper
# © 2005 jlaurens@users.sourceforge.net
iTM2_Engine_LaTeXDocExtractor_Version=1.0
iTM2LaTeXDocExtractorEngineUsage()
{
iTM2_USAGE="Welcome to $(basename "$0") version ${iTM2_Engine_LaTeXDocExtractor_Version}
This is iTeXMac2 built in script to wrap the LaTeX Documentation Extractor engine
($(which "$0"))
© 2005 jlaurens@users.sourceforge.net
Usage: $(basename "$0") with environment variables
	TWSMaster: the main input file, with an \"ins\" path extension"
echo "$iTM2_USAGE"
exit 0
}
"$iTM2_CMD_Notify" comment "Welcome to $(basename "$0") version ${iTM2_Engine_LaTeXDocExtractor_Version}
This is iTeXMac2 built in script to wrap the LaTeX Installation engine
© 2005 jlaurens@users.sourceforge.net"
iTM2_LaTeXDocExtractor_Engine="latex"
iTM2_LaTeXDocExtractor_EnginePath="$(which "${iTM2_LaTeXDocExtractor_Engine}")"
if ! [ -x "${iTM2_LaTeXDocExtractor_EnginePath}" ]
then
	"$iTM2_CMD_Notify" error "Unknown command ${iTM2_LaTeXDocExtractor_Engine}."
	iTM2DVIPDFMEngineUsage
fi
# removing the faraway project directory if any, first remove the trailing /'s
next:
iTM2_temp="echo ${iTM2_Faraway_Projects_Directory} | sed -e 's/\/$//'"
if [ ${#iTM2_temp} -lt ${#iTM2_Faraway_Projects_Directory} ]
then
	iTM2_Faraway_Projects_Directory="${iTM2_temp}"
fi
TWSMaster="${TWSMaster%${iTM2_Faraway_Projects_Directory}}"
if ! [ -e "${TWSMaster}"]
then
	popd
	exit 1
fi
"$iTM2_CMD_Notify" comment "TWSMaster is: ${TWSMaster}"
pushd "$(dirname "${TWSMaster}")"
INPUT_DIRECTORY="${PWD}"
INPUT="$(basename "${TWSMaster}")"
EXTENSION="${INPUT##*.}"
EXTENSION="$(echo "${EXTENSION}" | tr 'DTX' 'dtx')"
if [ "${EXTENSION}" != "DTX" ]
then
	popd
	exit 2
fi
"$iTM2_CMD_Notify" comment "Performing  ${iTM2_LaTeXDocExtractor_EnginePath} \"${INPUT}\""
${iTM2_LaTeXDocExtractor_EnginePath} "${INPUT}"
popd
if [ "${iTM2_Debug:-0}" != "0" ]
then
	"$iTM2_CMD_Notify" comment "$0 complete."
fi
# Missing a notification of the end of the work with success or failure
exit 0
