#!/usr/bin/env bash
# this is bbedit shell script for iTeXMac 1.3 version 0.1
# © 2006 jlaurens AT users DOT sourceforge DOT net
command="$(which mate)"
if ! [ ${#command} -gt 0 ]
then
	command="~/Applications/TextMate.app/Contents/Resources/mate"
	if ! [ -x "${command}" ]
	then
		command="/Applications/TextMate.app/Contents/Resources/mate"
		if ! [ -x "${command}" ]
		then
			echo "Where is Textmate?"
		fi
	fi
fi
if [ ${#file} -gt 0 ]
then
    options="-l ${line:-0}"
    echo "\"${command}\" ${options} \"${file}\""
    "${command}" ${options} "${file}"
else
    "${command}"
fi
exit

-l %d "%s"