#!/bin/sh -f
# this is iTM2_Engine_LaTeXInstaller wrapper
# © 2005 jlaurens@users.sourceforge.net
iTM2_Engine_LaTeXInstaller_Version=1.0
iTM2LaTeXInstallerEngineUsage()
{
iTM2_USAGE="Welcome to $(basename "$0") version ${iTM2_Engine_LaTeXInstaller_Version}
This is iTeXMac2 built in script to wrap the LaTeX Installer engine
($(which "$0"))
© 2005 jlaurens@users.sourceforge.net
Usage: $(basename "$0") with environment variables
	TWSMaster: the main input file, with an \"ins\" path extension"
echo "$iTM2_USAGE"
exit 0
}
"$iTM2_CMD_Notify" comment "Welcome to $(basename "$0") version ${iTM2_Engine_LaTeXInstaller_Version}
This is iTeXMac2 built in script to wrap the LaTeX Installation engine
© 2005 jlaurens@users.sourceforge.net"
iTM2_LaTeXInstaller_Engine="latex"
iTM2_LaTeXInstaller_EnginePath="$(which "${iTM2_LaTeXInstaller_Engine}")"
if ! [ -x "${iTM2_LaTeXInstaller_EnginePath}" ]
then
	"$iTM2_CMD_Notify" error "Unknown command ${iTM2_LaTeXInstaller_Engine}."
	iTM2DVIPDFMEngineUsage
fi
"$iTM2_CMD_Notify" comment "TWSMaster is: ${TWSMaster}"
pushd "$(dirname "${TWSMaster}")"
INPUT_DIRECTORY="${PWD}"
INPUT="$(basename "${TWSMaster}")"
EXTENSION="${INPUT##*.}"
EXTENSION="$(echo "${EXTENSION}" | tr 'INS' 'ins')"
if [ "${EXTENSION}" != "ins" ]
then
	popd
	exit 1
fi
"$iTM2_CMD_Notify" comment "Performing  ${iTM2_LaTeXInstaller_EnginePath} \"${INPUT}\""
${iTM2_LaTeXInstaller_EnginePath} "${INPUT}"
popd
if [ "${iTM2_Debug:-0}" != "0" ]
then
	"$iTM2_CMD_Notify" comment "$0 complete."
fi
# Missing a notification of the end of the work with success or failure
exit 0
