#!/usr/bin/env bash
# this is iTM2_Special for iTeXMac2 1.4
# © 2004 jlaurens AT users DOT sourceforge DOT net
iTM2_Special_version="1.0"
if [ "${iTM2ISSPECIALING:-0}" -gt 0 ]
then
    echo "iTM2: recursive call forbidden"
    exit 1
else
    iTM2ISSPECIALING=1
fi
iTM2_Special_RunSilently="${iTM2_RunSilently}"
iTM2_SPECIAL_USAGE="Welcome to `basename "$0"` version $iTM2_Special_version
This is iTeXMac2 built in script to special
Unfortunately I do not know how to special: override the default behaviour
© 2005 jlaurens AT users DOT sourceforge DOT net"
"${iTM2_CMD_Notify}" notify comment "$iTM2_SPECIAL_USAGE"
if [ "${iTM2_Special_RunSilently:-1}" -eq 0 ]
then
        "${iTM2_CMD_Notify}" notify comment "`basename "$0"` complete"
fi
exit
