#!/usr/bin/env bash
# this is iTM2_Bibliography for iTeXMac2 1.4
# © 2004jlaurens AT users DOT sourceforge DOT net
# the purpose of this script is to make the bibliography
# this script is distributed under the GPL
# If you plan to use this script, it would be fair to echo the original author jlaurens AT users DOT sourceforge DOT net and the product iTeXMac2
# 01/08/04 the .aux was not dropped down before calling bibtex
iTM2_Bibliography_Version="1.0"
iTM2_BIBLIOGRAPHY_USAGE="Welcome to $(basename "$0") version  $iTM2_Bibliography_Version
This is iTeXMac2 built in script to make the bibliography with BibTeX
© 2005 jlaurens AT users DOT sourceforge DOT net
Usage: $(basename "$0") options input where options are
       -h, --help: print this message and return.
       -e command, --engine command: replace bibtex by command.
           all other options are ignored.
           example: $(basename "$0") --engine \"bibtex -terse\"
       -q, --quiet: runs silently.
       -x, --minXReferences: the minimum number of cross references.
       -v, --verbose: does nothing special yet.
       -a, --all: process all the possible .aux files (recursive deep search).
       input is either a filename.aux, a directory name, or the current directory when void.
       The options given override some environment variables."
iTM2BibEngine=""
IFS='
'
#"
if [ "${iTM2_Debug:-0}" != "0" ]
then
	iTM2_Bibliography_RunSilently="${iTM2_Debug}"
	iTM2_CMD_Notify="iTM2_CMD_Gobble"
else
	iTM2_Bibliography_RunSilently="${iTM2_RunSilently}"
fi
if [ "${iTM2_Bibliography_RunSilently:-0}" != "0" ]
then
	iTM2_CMD_Notify="iTM2_CMD_Gobble"
else
	if [ "${iTM2_CMD_Notify:-0}" == "0" ]
	then
		iTM2_CMD_Notify="~/Library"
	fi
fi
while [ $# -gt 0 ]
do
	case $1 in
		-h|--help)
				"${iTM2_CMD_Notify}" notify comment "$iTM2_BIBLIOGRAPHY_USAGE"
		;;
		-e|--engine)
			shift 1
			if [ $# -gt 0 ]
			then
				iTM2BibEngine="$1"
				"${iTM2_CMD_Notify}" notify comment "iTM2: engine: $iTM2BibEngine"
			else
				"${iTM2_CMD_Notify}" notify comment "$iTM2_BIBLIOGRAPHY_USAGE"
			fi
		;;
		-q|--quiet)
			iTM2_Bibliography_RunSilently="YES"
		;;
		-x|--minXReferences)
                        shift 1
                        if [ $# -gt 0 ]
                        then
							iTM2_Bibliography_MinXReferences="$1"
                        else
							"${iTM2_CMD_Notify}" notify comment "$iTM2_BIBLIOGRAPHY_USAGE"
                        fi
		;;
		-a|--all)
			iTM2BibAll="YES"
		;;
		-v|--verbose)
			echo "iTM2: Verbose option when making the bibliography is not yet implemented"
		;;
		*)
			if [ ${#iTM2BibTargets} -gt 0 ]
			then
				iTM2BibTargets="$iTM2BibTargets$IFS"
			fi
			if [ -d ${1} ]
			then
				iTM2BibTargets="$iTM2BibTargets$(ls -1 -R $1)"
			else
				iTM2BibTargets="$iTM2BibTargets$1"
			fi
	esac
	shift 1
done
if [ "${iTM2_Bibliography_RunSilently:-1}" -eq 0 ]
then
        "${iTM2_CMD_Notify}" notify comment "Welcome to $(basename "$0") version $iTM2BibVersion
This is iTeXMac2 built in script to make the bibliography with BibTeX or another engine
© 2005 jlaurens AT users DOT sourceforge DOT net."
fi
if [ ${#iTM2BibEngine} == 0 ]
then
	iTM2BibEngine="bibtex"
	if [ ${iTM2_Bibliography_MinXReferences:-0} -gt 0 ]
	then
		iTM2BibEngine="${iTM2BibEngine} -min-crossrefs=${iTM2_Bibliography_MinXReferences}"
	fi
	if [ "${iTM2_Bibliography_RunSilently:-1}" -gt 0 ]
	then
		iTM2BibEngine="${iTM2BibEngine} -terse"	
	fi
fi
if [ "${iTM2_Bibliography_UseAuxName:-0}" -gt 0 ]
then
        TWSMaster="${iTM2_Bibliography_AuxName}"
fi
if [ ${#iTM2BibTargets} -eq 0 ]
then
	if [ ${#TWSMaster} -eq 0 ]
	then
		iTM2BibTargets="$(ls -1 -R *)$IFS"
	elif [ "${iTM2BibAll:-0}" -gt 0 ]
	then
		iTM2BibTargets="$(dirname ${TWSMaster}|ls -1 -R)$IFS"
	else
		iTM2BibTargets="${TWSMaster%.*}.aux"
	fi
fi
iTM2BibCurrent=""
for iTM2BibVar in ${iTM2BibTargets}
do
	if [ "${iTM2BibVar##*.}" == "aux" ]
	then
		if [ ${#iTM2BibCurrent} -gt 0 ]
		then
			iTM2BibVar="${iTM2BibCurrent}/${iTM2BibVar}"
		fi
			"${iTM2_CMD_Notify}" notify comment "Making the bibliography of: ${iTM2BibVar}"
		if [ -e "${iTM2BibVar}" ]
		then
			if [ "${iTM2BibVar%.*}.tex" -nt "${iTM2BibVar}" ]
			then
				"${iTM2_CMD_Notify}" notify warning "The LaTeX source file ${iTM2BibVar%.*}.tex is newer than ${iTM2BibVar}.
LaTeX bibliography ${iTM2BibVar%.*}.bbl not updated: Please compile first"
			elif [ "${iTM2BibVar}" -nt "${iTM2BibVar%.*}.bbl" ]
			then
				iTM2_BbCommand="${iTM2BibEngine} \"${iTM2BibVar%.*}\""
				"${iTM2_CMD_Notify}" notify comment "${iTM2_BbCommand}"
				eval "${iTM2_BbCommand}"
				if [ "$?" != "0" ]
				then
					status=1
				fi
#touch "${iTM2BibVar%.*}.bbl"
				"${iTM2_CMD_Notify}" notify comment "LaTeX bibliography ${iTM2BibVar%.*}.bbl updated";
			else
				"${iTM2_CMD_Notify}" notify comment "LaTeX bibliography ${iTM2BibVar%.*}.bbl is already up to date";
			fi
			if [ "${status:0}" != "0" ]
			then
				"${iTM2_CMD_Notify}" notify comment "FAILED";
			else
				"${iTM2_CMD_Notify}" notify comment "OK";
			fi
		fi
	else
		iTM2BibVar1="$(dirname ${iTM2BibVar})/$(basename ${iTM2BibVar} ":")"
		if [ "${iTM2BibVar}" == "${iTM2BibVar1}:" ]
		then
#			echo "this is a directory"
			iTM2BibCurrent="${iTM2BibVar1}"
#			echo "$iTM2BibCurrent"
		fi
	fi
done
if [ "${iTM2_Bibliography_RunSilently:-1}" == "0" ]
then
        "${iTM2_CMD_Notify}" notify comment "$(basename "$0") complete"
fi
exit $status
